"""add composite + diagnosis columns

Revision ID: 2bc1a4f10b76
Revises: b7ec68c3a4d8
Create Date: 2025-11-07 22:08:20.446970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc1a4f10b76'
down_revision = 'b7ec68c3a4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinical_diagnosis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pcos_awareness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pcos_symptoms_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('academic_pressure_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('academic_pressure_score')
        batch_op.drop_column('pcos_symptoms_score')
        batch_op.drop_column('pcos_awareness_score')
        batch_op.drop_column('clinical_diagnosis')

    # ### end Alembic commands ###
