"""add likert survey items

Revision ID: 5fc9b5ac97ee
Revises: 2bc1a4f10b76
Create Date: 2025-11-08 16:15:45.712186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc9b5ac97ee'
down_revision = '2bc1a4f10b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awareness_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('awareness_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('awareness_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('awareness_4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('awareness_5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('symptoms_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('symptoms_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('symptoms_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('symptoms_4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('symptoms_5', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('symptoms_5')
        batch_op.drop_column('symptoms_4')
        batch_op.drop_column('symptoms_3')
        batch_op.drop_column('symptoms_2')
        batch_op.drop_column('symptoms_1')
        batch_op.drop_column('academic_3')
        batch_op.drop_column('academic_2')
        batch_op.drop_column('academic_1')
        batch_op.drop_column('awareness_5')
        batch_op.drop_column('awareness_4')
        batch_op.drop_column('awareness_3')
        batch_op.drop_column('awareness_2')
        batch_op.drop_column('awareness_1')

    # ### end Alembic commands ###
